
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scaffolding_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: Ishan00
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: user-backend
    container_name: backend-service
    depends_on:
      - mysql
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/scaffolding_db
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    image: user-frontend
    container_name: frontend-service
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      REACT_APP_API_URL: http://backend:8090

volumes:
  mysql-data:
