name: Docker CI (Build & Push)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---------------- BACKEND ----------------
      - name: Build Backend Image
        run: |
          docker build \
            -t ishandhanusanka/user-backend:latest \
            -t ishandhanusanka/user-backend:${{ github.sha }} \
            ./backend

      - name: Push Backend Image
        run: |
          docker push ishandhanusanka/user-backend:latest
          docker push ishandhanusanka/user-backend:${{ github.sha }}

      # ---------------- FRONTEND ----------------
      - name: Build Frontend Image
        run: |
          docker build \
            -t ishandhanusanka/user-frontend:latest \
            -t ishandhanusanka/user-frontend:${{ github.sha }} \
            ./frontend

      - name: Push Frontend Image
        run: |
          docker push ishandhanusanka/user-frontend:latest
          docker push ishandhanusanka/user-frontend:${{ github.sha }}
